[project]
name = "uncoiled"
version = "0.1.0"
description = "Python status is: coiled and ready"
readme = "README.md"
authors = [
    { name = "Jonathan Sharpe", email = "mail@jonrshar.pe" }
]
requires-python = ">=3.8"
dependencies = []
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: ISC License (ISCL)",
    "Programming Language :: Python :: 3 :: Only"
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "fastapi>=0.115.5",
    "httpx>=0.27.2",
    "mypy>=1.13.0",
    "pytest>=8.3.3",
    "uvicorn>=0.32.0",
]
